groupName: acme.ionos.de

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: localhost:32000/cert-manager-webhook-ionos
  tag: 1.0.0
  pullPolicy: IfNotPresent

nameOverride: "cert-manager-webhook-ionos"
fullnameOverride: "cert-manager-webhook-ionos-chart"

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}