groupName: acme.ionos.de

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: localhost:32000/webhook-ionos
  tag: 1.0.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}